---
- name: Install Java, Git, and Apache Tomcat
  hosts: all
  become: yes
  tasks:
    - name: Install Git on Ubuntu
      apt:
        name: git
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Java for Ubuntu
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Git on CentOS
      yum:
        name: git
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Java for CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Download Apache Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz"
        dest: "/tmp/apache-tomcat-7.0.94.tar.gz"
      register: tomcat_download
      delegate_to: localhost

    - name: Extract Tomcat Archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-7.0.94.tar.gz"
        dest: "/opt/"
        remote_src: yes
      when: tomcat_download.changed

    - name: Set Permissions
      ansible.builtin.file:
        path: "/opt/apache-tomcat-7.0.94"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Start Apache Tomcat
      ansible.builtin.systemd:
        name: tomcat
        state: started
      ignore_errors: yes
