---
- name: Install Git, Java, and Apache Tomcat
  hosts: all
  become: yes
  vars:
    java_packages:
      CentOS: java-11
      Ubuntu: openjdk-11-jdk
      Debian: openjdk-11-jdk
      Linux: java-11
    tomcat_version: 7.0.94
    tomcat_version_minor: 0 # Define tomcat_version_minor here
  tasks:
    - name: Install Git on Amazon Linux
      dnf:
        name: git
        state: present
      when: ansible_pkg_mgr == "dnf" and ansible_distribution == "Amazon"

    - name: Debug Ansible facts for Amazon Linux
      debug: 
        var: ansible_pkg_mgr
      when: ansible_distribution == "Amazon"

    - name: Install Git on CentOS
      yum:
        name: git
        state: present
      when: ansible_pkg_mgr == "yum" and ansible_distribution == "CentOS"

    - name: Install Git on Ubuntu
      apt:
        name: git
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Install Java
      package:
        name: "{{ java_packages[ansible_distribution] }}"
        state: present
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

    - name: Update apt cache
      become: yes
      command: apt update
      when: ansible_distribution == "Ubuntu"

    - name: Install Java for Ubuntu
      become: yes
      apt:
        name: "{{ java_packages['Debian'] }}" # Corrected to 'Debian'
        state: present
      when: ansible_distribution == "Ubuntu"

- name: Install Apache Tomcat
  hosts: all
  become: yes
  tasks:
    - name: Download Apache Tomcat 7.0.94
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz"
        dest: "/tmp/apache-tomcat-7.0.94.tar.gz"

    - name: Extract Tomcat Archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-7.0.94.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Set Permissions
      file:
        path: "/opt/apache-tomcat-7.0.94"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes
        mode: "0755"

    - name: Start Apache Tomcat
      systemd:
        name: tomcat
        enabled: yes
        state: started
