---
- name: Install Git, Java, and Apache Tomcat
  hosts: all
  become: yes
  vars:
    java_packages:
      CentOS: java-1.8.0-openjdk
      Ubuntu: openjdk-8-jdk
      Debian: openjdk-8-jdk
      Linux: java-1.8.0-openjdk
    maven_version: 3.9.6
    tomcat_version: 9
    tomcat_version_minor: 0 # Define tomcat_version_minor here
  tasks:
    - name: Install Git
      package:
        name: git
        state: present

    - name: Install Java
      package:
        name: "{{ java_packages[ansible_distribution] }}"
        state: present
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

    - name: Install Java for Ubuntu
      become: yes
      apt:
        name: "{{ java_packages['Debian'] }}" # Corrected to 'Debian'
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache Tomcat
      become_user: root
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-{{ tomcat_version }}/v{{ tomcat_version }}.{{ tomcat_version_minor }}/bin/apache-tomcat-{{ tomcat_version }}.{{ tomcat_version_minor }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.{{ tomcat_version_minor }}.tar.gz"
      register: tomcat_download

    - name: Extract Tomcat tarball
      become_user: root
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.{{ tomcat_version_minor }}.tar.gz"
        dest: "/opt/"
        remote_src: yes
      when: tomcat_download.changed

    - name: Start Apache Tomcat
      systemd:
        name: tomcat
        enabled: yes
        state: started
